### PR TITLE
recipes-openamp: get rpmsg apps from new repo

### PR DESCRIPTION
**Pull request by wmamills**
remove rpmsg-echo-test, rpmsg-mat-mul and rpmsg-proxy-app source files and modify relative recipe to sync code from openamp-system-reference repo

Refactored rpmsg-example.inc by Bill Mills

* set a real and useful SHA1 hash by default so no AUTOREV
* Allow SRCREV to be overridden in mass in the local.conf file
* (:pn-xxx override is also possible)
* removed sha256sum, not used for git

Signed-off-by: Tanmay Shah <tanmay.shah@amd.com>
Signed-off-by: Bill Mills <bill.mills@linaro.org>

### CODE REVIEW

**Comment by wmamills** [comment]
I have refactored Tanmay's PR#22.
I will close that one.

The needed SW is in the corresponding repo now.
HOWEVER: we should make sure that the change that was in Mark's initial version of PR26 is included
Xilinx needs to test these new utilities to ensure that are still compatible with Petalinux 5.15/2022.x.
They were modified to work with 6.0+ kernels but SHOULD still work with older kernels.

**Comment by wmamills** [comment]
@TanmayShah-xilinx Can you please take a look.  I left your signed-off-by on it as you had done most of the work.

**Review by bentheredonethat — APPROVED** [review]

**Comment by TanmayShah-xilinx** [comment]
> @TanmayShah-xilinx Can you please take a look. I left your signed-off-by on it as you had done most of the work.

This looks good to me.

**Comment by mhatle** [comment]
Is this ready to be merged, or is there still work pending?

**Comment by TanmayShah-xilinx** [comment]
@wmamills, @mhatle I believe this is ready to be merged. If no further concerns then, can we merge it?

**Comment by wmamills** [comment]
@mhatle @bentheredonethat Please merge this at your convenience.  I don't want to mess up your nightly when you are not around.  I will be away from home until the 10th and my first (official) work day is the 17th

**Pull request merged**
