### PR TITLE
vendor/xilinx: meta-xilinx-standalone-experimental: Update to work wi…

### PR DESCRIPTION
**Pull request by bentheredonethat**
…th latest sources

As there has been a re-structuring of meta-openamp, there was a regression in support. This patch ensures that using latest SDT and OpenAMP overlays works with latest Lopper to generate OpenAMP DTs and apps for Versal and ZU+

additionally alo provide some formatting fixes in the recipes

### CODE REVIEW

**Comment by mhatle** [comment]
I've reviewed the changes.  They are specific to this vendor implementation so any risk of merging is very low, as only a specific configuration is affected.  As noted, the current implementation doesn't actually work.. which lowers the risk further.

**Comment by bentheredonethat** [comment]
ping @wmamills @edmooring  @TanmayShah-xilinx  for review

**Comment by bentheredonethat** [comment]
@arnopo  @wmamills  ping for review 

just trying to make a non AMD-Xilinx person reviews this.

Thank you

**Comment by wmamills** [comment]
I have tested the generic (non Xilinx) build w/ and w/o this commit and nothing gets rebuit so I think that garentees this is harmless for non-xilinx builds.  If you are happy with it, it is OK to merge.

**Pull request merged**
