### PR TITLE
recipes-openamp: get rpmsg apps from new repo

### PR DESCRIPTION
**Pull request by TanmayShah-xilinx**
remove rpmsg-echo-test source files and modify relative recipe to sync code from openamp-system-reference repo

Signed-off-by: Tanmay Shah <tanmay.shah@amd.com>

### CODE REVIEW

**Review by edmooring — APPROVED** [review]
Looks good to me.

**Comment by TanmayShah-xilinx** [comment]
@edmooring Thanks for approval. One minor change, we are moving LICENSE file to root directory in openamp-system-reference repo. So, I will have to change LICENSE file location in bitabake script.
I will send new patch soon.

**Comment by wmamills** [comment]
Most of this should be factored out of the individual recipes and made an inc file at the rpmsg-examples level.
I don't want to update 3 different places when adjusting the commit id.
Most of the new recipe logic should be there: git url etc.  Even the license can be done this way as they all refer to the same file.

The other thing that is strange here is pointing the WORKDIR deep into the repo clone.
This makes the LICENSE file:// URL very strange also.

I will look for a better way to do this.
One obvious answer is build them all with one recipe and then split them into separate packages.  However that is a lot of change compared to what we have and may not scale as well.

@mhatle may have other suggestions

**Comment by TanmayShah-xilinx** [comment]
> Most of this should be factored out of the individual recipes and made an inc file at the rpmsg-examples level. I don't want to update 3 different places when adjusting the commit id. Most of the new recipe logic should be there: git url etc. Even the license can be done this way as they all refer to the same file.

Ack.

> 
> The other thing that is strange here is pointing the WORKDIR deep into the repo clone. This makes the LICENSE file:// URL very strange also.
> 
> I will look for a better way to do this. One obvious answer is build them all with one recipe and then split them into separate packages. However that is a lot of change compared to what we have and may not scale as well.

Yes correct, we need better way to do this. I tried with making single bb file that compiles all the demos i.e. openamp-system-reference.bb, how ever it needs makefile in root dir. Which I believe wasn't good idea. I agreed with @arnopo and removed Makefile from root dir. So, I had to go all the way to example root dir where Makefile is available.

One solutiont could be, If we agree to keep Makefile in root dir, then we can call different targets from that make file from different recipes. Not sure if it's good idea though.

I definitely look forward to better and clean solution to this.

> 
> @mhatle may have other suggestions

**Comment by bentheredonethat** [comment]
LGTM

**Comment by wmamills** [comment]
If we go the single makefile route, I would not delete the individual ones.  Just add a new one that calls each of the sub makes.

However I am OK to merge 3 recipies and look for a better way over time.
I would still like to cleanup the LICENCE URL.  Can ${S} be used in a file:// URL??

**Comment by wmamills** [comment]
BTW: This will need to be rebased now that I have accepted the PRs from May

**Comment by wmamills** [comment]
Also please  change LICENSE to match the new master.  "BSD" gives warnings.  You need to specify which BSD.

**Comment by TanmayShah-xilinx** [comment]
> BTW: This will need to be rebased now that I have accepted the PRs from May

Sure I will do that.

**Comment by TanmayShah-xilinx** [comment]
> You can use WORKDIR in the LIC_FILES_CHKSUM.
> example:
> LIC_FILES_CHKSUM = "file://${WORKDIR}/license.html;md5=5c94767cedb5d6987c902ac850ded2c6"
> from:
> https://docs.yoctoproject.org/current/dev-manual/common-tasks.html#specifying-the-lic-files-chksum-variable

This sounds good idea. Thanks.

**Comment by TanmayShah-xilinx** [comment]
> If we go the single makefile route, I would not delete the individual ones. Just add a new one that calls each of the sub makes.

Actually I see that we may not need single make file, if we can accept that 

S = "${WORKDIR}/git/examples/linux/rpmsg-echo-test"

With this Makefile in root dir is not needed for now. We can introduce common Makefile if needed in future.

**Comment by wmamills** [comment]
Yes I am OK with that as long as we use ${WORKDIR} in the LIC_FILES_CHKSUM
WIth SRCURI and Licence info factored into an include common to all 3 examples.

**Comment by TanmayShah-xilinx** [comment]
> Yes I am OK with that as long as we use ${WORKDIR} in the LIC_FILES_CHKSUM
> WIth SRCURI and Licence info factored into an include common to all 3 examples.

One more thing. I did make common .inc file which will be included in all of the three .bb files.
However, for that to work, I may have to create single pull request and bring all the demo source files all togather in single commit. Otherwise it may break compilation.

**Comment by wmamills** [comment]
This PR is already a single commit.  I am OK with it staying that way.

**Comment by TanmayShah-xilinx** [comment]
> This PR is already a single commit. I am OK with it staying that way.

I am sorry I meant in https://github.com/OpenAMP/openamp-system-reference repository. 
Three demos should be available in single commit.

**Comment by TanmayShah-xilinx** [comment]
> This PR is already a single commit. I am OK with it staying that way.

I am sorry, I wasn't clear. I mean in openamp-system-reference repo: https://github.com/OpenAMP/openamp-system-reference 
We need all demos in single commit.

**Comment by mhatle** [comment]
I attempted to merge this request and got the following errors:

WARNING: rpmsg-proxy-app-1.0-r0 do_unpack: rpmsg-proxy-app: the directory ${WORKDIR}/git/examples/linux/rpmsg-proxy-app (/scratch2/fray/git/openamp/build-honister/tmp/work/core2-64-poky-linux/rpmsg-proxy-app/1.0-r0/git/examples/linux/rpmsg-proxy-app) pointed to by the S variable doesn't exist - please set S within the recipe to point to where the source has been unpacked to

WARNING: rpmsg-mat-mul-1.0-r0 do_unpack: rpmsg-mat-mul: the directory ${WORKDIR}/git/examples/linux/rpmsg-mat-mul (/scratch2/fray/git/openamp/build-honister/tmp/work/core2-64-poky-linux/rpmsg-mat-mul/1.0-r0/git/examples/linux/rpmsg-mat-mul) pointed to by the S variable doesn't exist - please set S within the recipe to point to where the source has been unpacked to

WARNING: rpmsg-echo-test-1.0-r0 do_unpack: rpmsg-echo-test: the directory ${WORKDIR}/git/examples/linux/rpmsg-echo-test (/scratch2/fray/git/openamp/build-honister/tmp/work/core2-64-poky-linux/rpmsg-echo-test/1.0-r0/git/examples/linux/rpmsg-echo-test) pointed to by the S variable doesn't exist - please set S within the recipe to point to where the source has been unpacked to


S is being set to:

S = "${WORKDIR}/git/examples/linux/rpmsg-echo-test"

The git checkout is empty, so your pull requests to git://github.com/OpenAMP/openamp-system-reference need to be approved before this can be merged.

Finally the SRCREV is set to 'AUTOREV' which will cause the system to pull data from GitHub on EVERY build.  Whatever the 1.0 release is, is what the SRCREV should point to.  Autorev will cause problems.

**Comment by wmamills** [comment]
I have reworded this PR as new PR#28.
I belive I have addressed @mhatle's concerns above.
I am closing this one in favor of that one.

**Pull request closed without merging**
