### PR TITLE
vendor/xilinx open-amp-xlnx: Add switch for Versal_net

### PR DESCRIPTION
**Pull request by bentheredonethat**
Pass switch to OpenAMP repo so that it can configure for Versal_net as needed.

### CODE REVIEW

**Comment by TanmayShah-xilinx** [comment]
Better commit title: add  versal-net platform support

Also commit message should explain what versal-net platform specific information is added in this commit.

**Comment by bentheredonethat** [comment]
@TanmayShah-xilinx  i updated commit message. thanks for review

**Comment by bentheredonethat** [comment]
@wmamills  ping for review

**Comment by bentheredonethat** [comment]
@wmamills  @mhatle  ping for review

**Comment by bentheredonethat** [comment]
@wmamills  @mhatle  ping for review

**Review by wmamills — APPROVED** [review]
This only effects Xilinx specific builds.  If the AMD/Xilinx CI is happy with this I am fine with it as well.

**Comment by wmamills** [comment]
@bentheredonethat What is the status of this?  I approved  on Jun 6.  Do you still need it?

**Comment by bentheredonethat** [comment]
@wmamills  yes

**Pull request merged**
