### PR TITLE
recipes-openamp: rpmsg-examples: Use latest commit

### PR DESCRIPTION
**Pull request by bentheredonethat**
Latest commit updates usage of driver unload/load in rpmsg-kernel-space apps

Signed-off-by: Ben Levinsky <ben.levinsky@amd.com>

### CODE REVIEW

**Comment by bentheredonethat** [comment]
CC @arnopo  @mhatle  @TanmayShah-xilinx

**Comment by wmamills** [comment]
Looks fine to me.  I have not done a test build for this but am OK to merge anyway

**Comment by wmamills** [comment]
Since the commits that this point to are reviwed and merged by @arnopo I am OK with this being merged.
If there is any objection please speak up.
Otherwise I will merge it tomorrow Feb 15.

**Comment by mhatle** [comment]
I've merged it.. thanks for the reviews.

**Pull request merged**
