### PR TITLE
Fix vendor/xilinx kernel integration

### PR DESCRIPTION
**Pull request by mhatle**
The linux integration was using the same name as the base linux kmeta, causing a collision and resulting in being unable to find one or the other config files.  This moves the vendor version to openamp-xilinx-kmeta and resolves the issue.  (The pull request includes the contents of pull request 23 as well.)

### CODE REVIEW

**Comment by bentheredonethat** [comment]
@mhatle  LGTM

**Review by wmamills — CHANGES_REQUESTED** [review]
rpmsg-mat-mul and other Linux demo are being moved out of this layer.
Coordinate with Tanmay about getting this change into the version being used.
If you drop this patch the rest looks OK for now.
In the future we still need to talk about the proper place for vendor support

**Comment by mhatle** [comment]
Staged to master-next

**Comment by mhatle** [comment]
Code has been pushed to master.

**Pull request closed without merging**
