### PR TITLE
Update Libmetal and OpenAMP recipes for SDT flow with latest sources

### PR DESCRIPTION
**Pull request by bentheredonethat**

### CODE REVIEW

**Comment by bentheredonethat** [comment]
CC @wmamills  @mhatle

**Comment by mhatle** [comment]
I've reviewed this.  The 3rd change is tied to the 'meta-xilinx-standalone-experimental' via the existing dynamic layers configuration.  So should be benign in a 'normal workflow'.  The remaining changes appear safe to me.

No concerns.

Acked-by: Mark Hatle <mark.hatle@amd.com>

**Comment by bentheredonethat** [comment]
currently there is boot issue in lopper-generated linux DTB so testing with latest is blocked. I will probably have to do one more push after lopper issue is resolved. For lets wait on review/merge actions.

**Comment by bentheredonethat** [comment]
currently tested and working:
Libmetal on ZynqMP and Versal
OpenAMP on ZynqMP and Versal for Firmware generation and Linux DT OpenAMP information.

**Comment by bentheredonethat** [comment]
ping for review @mhatle  @wmamills

**Comment by bentheredonethat** [comment]
ping for review @edmooring  @tnmysh

**Comment by mhatle** [comment]
Code has been merged.  Low risk, only affects vendor/xilinx.

**Pull request merged**
